---
title: "BC2"
author: "Francesco Massaini"
date: "2024-03-28"
output: html_document
---

# Imports
```{r Imports}
library(dplyr)
library(tibble)
library(tidyr)
library(org.Hs.eg.db) # Homo sapiens db
library(stringr)
library(RColorBrewer) # for plot
library(pheatmap) # for heatmaps
library(ADImpute) # This package provides functions to compute TPM
library(ggplot2)
library(FactoMineR)
library(factoextra)
```

# Functions
```{r Functions}
# Remove version number from ENSEMBL ID
remove_gene_version <- function(df_with_gene_version) {
  rownames(df_with_gene_version) <- rownames(df_with_gene_version) %>% 
    str_remove("\\..*$") 
  return(as.data.frame(df_with_gene_version))
}

# Converting from ENSEMBL ID to GENE SYMBOL. Use org.Hs.eg.db db 
EnsemblID_to_GeneSymbol <- function(raw_counts_file){
  entrz <- AnnotationDbi::select(org.Hs.eg.db, keys = rownames(raw_counts_file), columns = "SYMBOL", keytype = "ENSEMBL") # keys are the data to overlap. columns is the column to replace and keytype is the column where to find corrispondences   # entrz is a df storing ENSEMBL ID and GENE SYMBOLS. ENSEMBL ID are selected by the ROW NAMES of your raw_counts_file 
  raw_counts_file <- raw_counts_file %>%
    mutate(ENSEMBL = rownames(raw_counts_file)) %>% # add a column
    inner_join(., entrz, by="ENSEMBL") %>% # join, merge df with a common column (ENSEMBL)
    dplyr::filter(!is.na(SYMBOL)) %>%
    distinct(SYMBOL, .keep_all = T) %>% # keep only one variable of the duplicated symbols
    column_to_rownames("SYMBOL") %>% 
    dplyr::select(., -c("ENSEMBL"))
return(raw_counts_file)  
}

# Raw counts to TPM. Need GENE SYMBOL!
counts_to_TPM <- function(raw_counts_file){
  # log2(TPM+1) 
  TPM <- ADImpute::NormalizeTPM(raw_counts_file, log = T)
return(TPM)  
}

# Plots - Heatmap
Compute_Samples_Heatmap <- function(df){
  df <- as.matrix(df)
  
  # Utilizes the NormalizeTPM function from the ADImpute package.
  # Performs normalization on the 'TPM' data frame, considering TPM (Transcripts Per Million) values.
  # Setting 'log = T' indicates that the normalization will be done using the logarithm of TPM values.
  # This is often employed to reduce variance and approximate a normal distribution.
  # Add 1 at the log log(TPM+1) so that 0 values are propertly calculated
  
  sampleDists <- dist(t(df), method = 'euclidean') #Compute distance of the matrix. DO NOT DO IT FOR GENES. dist take into account rows! So to look at the patients you need to transpose. Distance is computed with eucledian metric. Remember you need to transpose (t) the matrix because dist takes rows (and samples are into columns) 
  sampleDistMatrix <- as.matrix(sampleDists)
  colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
  pheatmap(sampleDistMatrix,    main = "Samples heatmap", sub="", xlab="",
       cex.lab = 1, cex.axis = 1, cex.main = 2, clustering_method = 'complete')
}

# Plots - Dendrogram
Compute_Samples_dendrogram <- function(df){
  sampleTree = hclust(dist(t(df), method = 'euclidean'), method = "complete");
  plot(sampleTree, main = "Samples dendrogram", sub="", xlab="", 
       cex.lab = 1, cex.axis = 1, cex.main = 2)
}

```

# Path and folders
```{r Data loading}
path <- c("/home/francesco.massaini/Desktop/IMMUCAN_data/BC2/02_TPM/BC2_estimated_TPM.RData")
files_names <- gsub(".txt$", "", basename(path))
folders_names <- strsplit(path, "IMMUCAN_data")
folders_names <- folders_names[[1]][2]
folders_names <- strsplit(folders_names, split = files_names)


samples_list <- read.table("/home/francesco.massaini/Desktop/IMMUCAN_data/BC2/Patient_to_include_from_rna_samples_bc2_to_create_custom_cohort.tsv", header = TRUE, sep = "\t")

# for loop in Counts_to_TPM

```

# load and processign data from RData
```{r Processing RData}
# Load RData
load(path)

# Convert ENSEMBL ID with GENE SYMBOL
TPM <- remove_gene_version(gexp_tpm)
TPM <- EnsemblID_to_GeneSymbol(TPM)
```

# BC2 Filtering Samples and saving file
```{r Filtering samples}
# Filtering samples with the list samples_list
BC2_samples <- intersect(colnames(TPM), samples_list$sample)
BC2 <- TPM[BC2_samples] 


files_names[1] = "BC2_TPM" # Change file name manually if you need
```


# Analizing TPM
```{r Distribution}
# Bar plot to see TPM distribution

BC2_long <- pivot_longer(BC2, cols = 2:ncol(BC2), names_to = "Samples", values_to = "TPM")

# Summary
# summary(dplyr::select(BC2, !Genes))

# Histogram
ggplot(data = BC2_long, aes(x=TPM)) + 
  geom_histogram(binwidth = 1000) +
  geom_rug(color = "blue") +
  scale_x_continuous(limits = c(-100, max(BC2_long$TPM))) +
  scale_y_log10()
  # scale_y_continuous(limits = c(-100, 800000))

# Jitter plot  
ggplot(data = BC2_long, aes(x = TPM, y = 0)) +
  geom_jitter(width = 0, height = 0.1, size = 1, alpha = 0.5) +
  xlab("TPM") +
  ylab("")
```
```{r Heatmap and dendrogram}
# Heatmap and dendrogram to see patient outliers
png(paste0("../IMMUCAN_data/", folders_names[[i]][1], "/02_Plot_Outliers/", files_names[i],"_outliers"), width = 16)
png(paste0("../IMMUCAN_data/", folders_names[[i]][1], "/02_Plot_Outliers/", files_names[i],"_outliers"), width = ) # folders_names[[i]][1] double square bracket to access to the i vector, single bracket to access to the first value of the i vector 
TPM_Heatmap(BC2)
dev.off()

TPM_Sample_dendrogram(BC2)


```

```{r PCA}
# PCA biplot on TPM

pca_result <- PCA(t(BC2), scale.unit = TRUE, graph = FALSE) # t(BC2) because PCA takes rows 
fviz_eig(pca_result)
fviz_pca_ind(pca_result, geom.ind = "point")
factoextra::fviz_pca_biplot(pca_result, repel = T, select.var = list(contrib = 5), label = "var") # repel = T do not overlap the text, select.var = list(contrib = 5) shows only the most 5 variable feature (variables) that contributes to separation. label = var , put label ONLY on the 5 variables
```

# TO DO
```{r}
 
# Analisi Risultati di deconvoluzione in termini di stackable histograms
# heatmap sui samples e PCA sulla deconvoluzione

# CellTFusion
```


# Saving file
```{r Saving file}

BC2 <- rownames_to_column(BC2, "Genes") 
# Write file in the correct format for deconvolution

write.table(BC2, file = paste0("../IMMUCAN_data", folders_names[[1]][1], files_names[1],"_fromRdata.txt"), quote = F, sep = "\t", row.names = F)
message(paste("File saved in", paste0("../IMMUCAN_data", folders_names[[1]][1], files_names[1],"_fromRdata.txt")) )
```

