library(stringr)
library(dplyr)
library(readxl)

# Function to load phenotype keys
load_phenotype_keys <- function(phenotype_keys_path, current_IF) {
  phenotype_keys_file <- paste0(phenotype_keys_path, "phenotype_key_", current_IF, ".csv")
  phenotype_keys <- read.csv(phenotype_keys_file)
  print(paste("Phenotype keys:", phenotype_keys_file))
  return(phenotype_keys)
}

# Function to process tissue type (create cell types frequency df)
process_tissue_type <- function(df, tissue_type, IF_dir, current_IF, save_files, file_name) {
  tissue_df <- df %>% filter(tissue_type == tissue_type)
  celltype_freq <- as.data.frame(table(tissue_df$sample_ID, tissue_df$celltype))
  colnames(celltype_freq) <- c("sample_ID", "celltypes", "Freq")
  celltype_freq <- celltype_freq %>% mutate(tissue_type = tissue_type)
  
  if (save_files) {
    write.csv(celltype_freq, paste0(IF_dir, current_IF, file_name, tissue_type, "_cell_freq.csv"), row.names = FALSE)
  }
}

# Function to load patient lists
load_patients_list <- function(file_path, panel) {
  read_excel(file_path) %>%
    mutate(panel = panel) %>%
    rename(tissue_type_Andrea = tissue_type)
}

# Main function to process IF files for individual patients
process_individual_IF_files <- function(IF_path, phenotype_keys_path, current_IF, save_files = FALSE) {
  IF_dir <- paste0(IF_path, current_IF, "/")
  print(paste("Processing directory:", IF_dir))
  
  all_files <- list.files(IF_dir)
  file_info <- file.info(file.path(IF_dir, all_files))
  
  # Filter only files (not directories)
  only_files <- all_files[!file_info$isdir]
  
  # Load phenotype keys
  phenotype_keys <- load_phenotype_keys(phenotype_keys_path, current_IF)
  
  all <- data.frame()
  patient_counter <- 1
  total_patients <- length(only_files) - sum(grepl("_all_patients_", only_files) | grepl("_filtered_patients_", only_files))
  
  for (file in only_files) {
    
    # Skip files generated by previous runs
    if (grepl("_all_patients_", file) || grepl("_filtered_patients_", file)) {
      next
    }
    
    print(paste("Processing patient", patient_counter, "of", total_patients, ":", file))
    patient_counter <- patient_counter + 1
    file_path <- paste0(IF_dir, file)
    
    if (file.info(file_path)$size > 0) {
      df <- read.delim(file_path, sep = "\t") %>%
        select(cell.ID, nucleus.x, nucleus.y, tissue.type, phenotype) %>%
        left_join(phenotype_keys, by = "phenotype") %>%
        mutate(celltype = coalesce(celltype, phenotype),
               file_name = file,
               sample_panel_ID = str_split_i(file, "_#", 1),
               sample_ID = str_split_i(file, "-IF\\d", 1),
               patient_ID = str_split_i(file, "-FIXT", 1),
               panel_ID = str_extract(file, "IF\\d-0\\d"),
               panel = str_extract(file, "IF\\d"))
      colnames(df) <- str_replace_all(colnames(df), "\\.", "_")
      all <- rbind(all, df)
    } else {
      print(paste("File is empty, skipping:", file))
    }
  }
  
  if (save_files) {
    write.csv(all, paste0(IF_dir, current_IF, "_all_patients_cell_coord.csv"), row.names = FALSE)
  }
  
  return(all)
}

# Function to filter patients from combined data
filter_patients <- function(all_data, IFs, IF_dir, current_IF, save_files = FALSE) {
  IF_patients_filtered <- all_data %>%
    inner_join(IFs, by = c("sample_ID" = "sample", "panel" = "panel"))
  cat("Total rows after filtering:", nrow(IF_patients_filtered), "\nTotal samples:", length(unique(IF_patients_filtered$sample_ID)), "\n")
  
  if (save_files) {
    write.csv(IF_patients_filtered, paste0(IF_dir, current_IF, "_filtered_patients_Andrea.csv"), row.names = FALSE)
  }
  
  return(IF_patients_filtered)
}

# Paths
IF_path <- "../IMMUCAN_data/BC2/01_Imaging/IF/"
phenotype_keys_path <- "../IMMUCAN_data/Phenotype_keys_from_GitHub/"

# Process IF1
IF1_data <- process_individual_IF_files(IF_path, phenotype_keys_path, "IF1", save_files = TRUE)
process_tissue_type(IF1_data, "tumor", paste0(IF_path, "IF1/"), "IF1", save_files = TRUE, file_name = "_all_patients_")
process_tissue_type(IF1_data, "stroma", paste0(IF_path, "IF1/"), "IF1", save_files = TRUE, file_name = "_all_patients_")

# Process IF2
IF2_data <- process_individual_IF_files(IF_path, phenotype_keys_path, "IF2", save_files = TRUE)
process_tissue_type(IF2_data, "tumor", paste0(IF_path, "IF2/"), "IF2", save_files = TRUE, file_name = "_all_patients_")
process_tissue_type(IF2_data, "stroma", paste0(IF_path, "IF2/"), "IF2", save_files = TRUE, file_name = "_all_patients_")

# Process IF3
IF3_data <- process_individual_IF_files(IF_path, phenotype_keys_path, "IF3", save_files = TRUE)
process_tissue_type(IF3_data, "tumor", paste0(IF_path, "IF3/"), "IF3", save_files = TRUE, file_name = "_all_patients_")
process_tissue_type(IF3_data, "stroma", paste0(IF_path, "IF3/"), "IF3", save_files = TRUE, file_name = "_all_patients_")

# Load patient lists for each panel
IF1_patients_list <- load_patients_list("../IMMUCAN_data/BC2/01_Reference_files_from_Andrea_BC2_TNBC/List_samples_data_type/mif1_samples_bc2_custom_cohort.xlsx", "IF1")
IF2_patients_list <- load_patients_list("../IMMUCAN_data/BC2/01_Reference_files_from_Andrea_BC2_TNBC/List_samples_data_type/mif2_samples_bc2_custom_cohort.xlsx", "IF2")
IF3_patients_list <- load_patients_list("../IMMUCAN_data/BC2/01_Reference_files_from_Andrea_BC2_TNBC/List_samples_data_type/mif3_samples_bc2_custom_cohort.xlsx", "IF3")

# Combine patient lists
IFs <- bind_rows(IF1_patients_list, IF2_patients_list, IF3_patients_list)
cat("Total IFs rows (repeated samples):", nrow(IFs), "\n")

# Optionally save combined patient lists
write.csv(IFs, "../IMMUCAN_data/BC2/01_Reference_files_from_Andrea_BC2_TNBC/List_samples_data_type/ALL_mIFs_samples_bc2_custom_cohort.csv", row.names = FALSE)

# Filter and process patients for IF1
IF1_patients_filtered <- filter_patients(IF1_data, IFs, paste0(IF_path, "IF1/"), "IF1", save_files = TRUE)
process_tissue_type(IF1_patients_filtered, "tumor", paste0(IF_path, "IF1/"), "IF1", save_files = TRUE, file_name = "_filtered_patients_")
process_tissue_type(IF1_patients_filtered, "stroma", paste0(IF_path, "IF1/"), "IF1", save_files = TRUE, file_name = "_filtered_patients_")

# Filter and process patients for IF2
IF2_patients_filtered <- filter_patients(IF2_data, IFs, paste0(IF_path, "IF2/"), "IF2", save_files = TRUE)
process_tissue_type(IF2_patients_filtered, "tumor", paste0(IF_path, "IF2/"), "IF2", save_files = TRUE, file_name = "_filtered_patients_")
process_tissue_type(IF2_patients_filtered, "stroma", paste0(IF_path, "IF2/"), "IF2", save_files = TRUE, file_name = "_filtered_patients_")

# Filter and process patients for IF3
IF3_patients_filtered <- filter_patients(IF3_data, IFs, paste0(IF_path, "IF3/"), "IF3", save_files = TRUE)
process_tissue_type(IF3_patients_filtered, "tumor", paste0(IF_path, "IF3/"), "IF3", save_files = TRUE, file_name = "_filtered_patients_")
process_tissue_type(IF3_patients_filtered, "stroma", paste0(IF_path, "IF3/"), "IF3", save_files = TRUE, file_name = "_filtered_patients_")

# Directory structure
# ../IMMUCAN_data/
#   └── BC2/
#       └── 01_Imaging/
#           └── IF/
#               ├── IF1/
#               ├── IF2/
#               └── IF3/
#       └── 01_Reference_files_from_Andrea_BC2_TNBC/
#           └── List_samples_data_type/
#               ├── mif1_samples_bc2_custom_cohort.xlsx
#               ├── mif2_samples_bc2_custom_cohort.xlsx
#               └── mif3_samples_bc2_custom_cohort.xlsx
#   └── Phenotype_keys_from_GitHub/
#       ├── phenotype_key_IF1.csv
#       ├── phenotype_key_IF2.csv
#       └── phenotype_key_IF3.csv
