---
title: "RAW_COUNTS_TO_TPM"
author: "Francesco Massaini"
date: "2024-03-18"
output: pdf_document
---

# Inputs are the old version of Marcelo 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Imports

```{r Imports}
library(tidyverse)
library(tibble)
library(org.Hs.eg.db) # Homo sapiens db
library(ADImpute) # to normalize with gene lenght
library(RColorBrewer) # for plot
library(pheatmap) # for heatmaps
library(ADImpute) # This package provides functions for imputing missing data

```

# Functions 

```{r Functions}
# library(org.Hs.eg.db) # Homo sapiens db
# columns(org.Hs.eg.db) # to look at the columns of this db

# Raw counts to TPM
counts2TPM <- function(raw_counts_file){
  entrz <- AnnotationDbi::select(org.Hs.eg.db, keys = rownames(raw_counts_file), columns = "SYMBOL", keytype = "ENSEMBL") # keys are the data to overlap. columns is the column to replace and keytype is the column where to find corrispondences   # entrz is a df storing ENSEMBL ID and GENE SYMBOLS. ENSEMBL ID are selected by the ROW NAMES of your raw_counts_file 
  raw_counts_file <- raw_counts_file %>%
    mutate(ENSEMBL = rownames(raw_counts_file)) %>% # add a column
    inner_join(., entrz, by="ENSEMBL") %>% # join, merge df with a common column (ENSEMBL)
    dplyr::filter(!is.na(SYMBOL)) %>%
    distinct(SYMBOL, .keep_all = T) %>% # keep only one variable of the duplicated symbols
    column_to_rownames("SYMBOL") %>% 
    dplyr::select(., -c("ENSEMBL")) 
  TPM <- ADImpute::NormalizeTPM(raw_counts_file, log = T)
return(TPM)  
}

# Plots - Heatmap
TPM_Heatmap <- function(TPM){
  TPM <- as.matrix(TPM)
  
  # Utilizes the NormalizeTPM function from the ADImpute package.
  # Performs normalization on the 'TPM' data frame, considering TPM (Transcripts Per Million) values.
  # Setting 'log = T' indicates that the normalization will be done using the logarithm of TPM values.
  # This is often employed to reduce variance and approximate a normal distribution.
  # Add 1 at the log log(TPM+1) so that 0 values are propertly calculated
  
  sampleDists <- dist(t(TPM)) #Compute distance of the matrix. DO NOT DO IT FOR GENES. dist take into account rows! So to look at the patients you need to transpose. Distance is computed with eucledian metric. Remember you need to transpose (t) the matrix because dist takes rows (and samples are into columns) 
  sampleDistMatrix <- as.matrix(sampleDists)
  colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
  pheatmap(sampleDistMatrix,    main = "Sample clustering to detect outliers", sub="", xlab="",
       cex.lab = 1.5, cex.axis = 1.5, cex.main = 2)
}
```




```{r Data Loading and plots}
# Data Loading

path <- c("/home/francesco.massaini/Desktop/IMMUCAN_data/BC2/01_Raw_Counts/BC2_COUNTS.txt",
          "/home/francesco.massaini/Desktop/IMMUCAN_data/BC3/01_Raw_Counts/BC3_COUNTS.txt",
          "/home/francesco.massaini/Desktop/IMMUCAN_data/NSCLC/01_Raw_Counts/NSCLC_COUNTS.txt")
files_names <- gsub(".txt$", "", basename(path))
folders_names <- strsplit(files_names, "_")

# EDA
for (i in 1:length(path)) {
  counts <- read.table(path[i], header = TRUE,  sep = '	', row.names = 1)
  TPM <- counts2TPM(counts) 
  pdf(paste0("../IMMUCAN_data/", folders_names[[i]][1], "/02_Plot_Outliers/", files_names[i],"_outliers"), width = 16) # folders_names[[i]][1] double square bracket to access to the i vector, single bracket to access to the first value of the i vector 
  TPM_Heatmap(TPM)
  TPM_Sample_dendrogram(TPM)
  dev.off()
  TPM <- data.frame(TPM) %>%
    rownames_to_column("Genes")
  write.table(TPM, file = paste0("../IMMUCAN_data/", folders_names[[i]][1], "/02_TPM/", files_names[i],"_TPM.txt"), quote = F, sep = "\t", row.names = F)
}
```
