---
title: "NSCLC2"
author: "Francesco Massaini"
date: "2024-03-28"
output: html_document
---

# Imports
```{r Imports}
library(dplyr)
library(tibble)
library(tidyr)
library(org.Hs.eg.db) # Homo sapiens db
library(stringr)
library(RColorBrewer) # for plot
library(pheatmap) # for heatmaps
library(ADImpute) # This package provides functions to compute TPM
library(ggplot2)
library(FactoMineR)
library(factoextra)
```

# Functions
```{r Functions}
# Remove version number from ENSEMBL ID
remove_gene_version <- function(df_with_gene_version) {
  rownames(df_with_gene_version) <- rownames(df_with_gene_version) %>% 
    str_remove("\\..*$") 
  return(as.data.frame(df_with_gene_version))
}

# Converting from ENSEMBL ID to GENE SYMBOL. Use org.Hs.eg.db db 
EnsemblID_to_GeneSymbol <- function(raw_counts_file){
  entrz <- AnnotationDbi::select(org.Hs.eg.db, keys = rownames(raw_counts_file), columns = "SYMBOL", keytype = "ENSEMBL") # keys are the data to overlap. columns is the column to replace and keytype is the column where to find corrispondences   # entrz is a df storing ENSEMBL ID and GENE SYMBOLS. ENSEMBL ID are selected by the ROW NAMES of your raw_counts_file 
  raw_counts_file <- raw_counts_file %>%
    mutate(ENSEMBL = rownames(raw_counts_file)) %>% # add a column
    inner_join(., entrz, by="ENSEMBL") %>% # join, merge df with a common column (ENSEMBL)
    dplyr::filter(!is.na(SYMBOL)) %>%
    distinct(SYMBOL, .keep_all = T) %>% # keep only one variable of the duplicated symbols
    column_to_rownames("SYMBOL") %>% 
    dplyr::select(., -c("ENSEMBL"))
return(raw_counts_file)  
}

# Raw counts to TPM. Need GENE SYMBOL!
counts_to_TPM <- function(raw_counts_file){
  # log2(TPM+1) 
  TPM <- ADImpute::NormalizeTPM(raw_counts_file, log = T)
return(as.data.frame(TPM))  
}


# Plots - Heatmap
Compute_Samples_Heatmap <- function(df){
  df <- as.matrix(df)
  
  # Utilizes the NormalizeTPM function from the ADImpute package.
  # Performs normalization on the 'TPM' data frame, considering TPM (Transcripts Per Million) values.
  # Setting 'log = T' indicates that the normalization will be done using the logarithm of TPM values.
  # This is often employed to reduce variance and approximate a normal distribution.
  # Add 1 at the log log(TPM+1) so that 0 values are propertly calculated
  
  sampleDists <- dist(t(df), method = 'euclidean') #Compute distance of the matrix. DO NOT DO IT FOR GENES. dist take into account rows! So to look at the patients you need to transpose. Distance is computed with eucledian metric. Remember you need to transpose (t) the matrix because dist takes rows (and samples are into columns) 
  sampleDistMatrix <- as.matrix(sampleDists)
  colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
  pheatmap(sampleDistMatrix,    main = "Samples heatmap", sub="", xlab="",
       cex.lab = 1, cex.axis = 1, cex.main = 2, clustering_method = 'complete')
}

# Plots - Dendrogram
Compute_Samples_dendrogram <- function(df){
  sampleTree = hclust(dist(t(df), method = 'euclidean'), method = "complete");
  plot(sampleTree, main = "Samples dendrogram", sub="", xlab="", 
       cex.lab = 1, cex.axis = 1, cex.main = 2)
}


# Correlation
cors <- function(df) {
  M <- Hmisc::rcorr(as.matrix(df))
  Mdf <- map(M, ~data.frame(.x))
  return(Mdf)
}

formatted_cors <- function(df){
  cors(df) %>%
    map(~rownames_to_column(.x, var="measure1")) %>%
    map(~pivot_longer(.x, -measure1, names_to = "measure2", values_to = "value")) %>%
    bind_rows(.id = "id") %>%
    pivot_wider(names_from = id, values_from = value) %>%
    mutate(sig_p = ifelse(P < .05, T, F),
           p_if_sig = ifelse(sig_p, P, NA),
           r_if_sig = ifelse(sig_p, r, NA)) 
}

```

# Path and folders
```{r Data loading}
# Imposta il percorso della cartella
input_folder <- "/home/francesco.massaini/Desktop/IMMUCAN_data/NSCLC2/01_Raw_Counts/star_counts"
output_folder <- "/home/francesco.massaini/Desktop/IMMUCAN_data/NSCLC2/02_TPM/"

# Ottieni tutti i file .txt nella cartella
txt_input_files <- list.files(path = input_folder, pattern = "\\.txt$", full.names = TRUE)

# Stampa il contenuto della variabile txt_files
# print(txt_input_files)

files_names <- gsub(".txt$", "", basename(txt_input_files))
samples_names = str_split_i(files_names, "_", 1)

```

# load and processign data NSCLC2
```{r Processing Raw Counts}

# Merging all the patients files, filtering rows of input files, removing gene version, and converting to GENE SYMBOLS

merged_counts <- read.delim(txt_input_files[1], header = 0, row.names = 1)
colnames(merged_counts) <- samples_names[1]

for (i in 2:length(txt_input_files)) {
  # print(i)
    # Leggi il data frame successivo
  counts <- read.delim(txt_input_files[i], header = 0, row.names = 1)
  colnames(counts) <- samples_names[i]
  # print(samples_names[i])
  # Unisci le colonne del nuovo data frame a merged_counts
  merged_counts <- cbind(merged_counts, counts)
}
  merged_counts <- merged_counts %>%
    filter(!rownames(.) %in% c("__no_feature", "__ambiguous", "__too_low_aQual", "__not_aligned", "__alignment_not_unique")) %>%
    remove_gene_version() %>%
    EnsemblID_to_GeneSymbol()

# ADImpute to normalize to TPM
TPM <- counts_to_TPM(merged_counts)
```

# Analizing TPM
```{r Distribution}
# Summary
summary(TPM)

TPM_long <- pivot_longer(TPM, cols = 2:ncol(TPM), names_to = "Samples", values_to = "TPM")
# Histogram
ggplot(data = TPM_long, aes(x=TPM)) + 
  geom_histogram(binwidth = 0.05) +
  geom_rug(color = "blue") +
  scale_x_continuous(limits = c(0, max(TPM_long$TPM))) +
  scale_y_continuous(limits = c(0, 100000))
# scale_y_continuous(limits = c(-100, 800000))

# Jitter plot  
ggplot(data = TPM_long, aes(x = TPM, y = 0)) +
  geom_jitter(width = 0, height = 0.1, size = 1, alpha = 0.5) +
  xlab("TPM") +
  ylab("")
```
# TPM Analysis
```{r Heatmap and dendrogram}
# Heatmap and dendrogram to see patient outliers on TPM

output_folder_TPM_outlier <- paste0(str_split_i(output_folder, "02_TPM/", 1), "02_Plot_Outliers/")

# pdf(paste0(output_folder_TPM_outlier, "TPM_samples_heatmap.pdf"), width = 16, height = 16)
png(paste0(output_folder_TPM_outlier, "TPM_samples_heatmap.png"), width = 2000, height = 2000)
Compute_Samples_Heatmap(TPM)
dev.off()
# dev.off()

# pdf(paste0(output_folder_TPM_outlier, "TPM_samples_dendrogram.pdf"))
png(paste0(output_folder_TPM_outlier, "TPM_samples_dendrogram.png"), width = 2000, height = 1000)
Compute_Samples_dendrogram(TPM)
dev.off()
# dev.off()


# PCA biplot on TPM

pca_result <- PCA(t(TPM), scale.unit = TRUE, graph = FALSE) # t(BC2) because PCA takes rows 
fviz_eig(pca_result)

# pdf(paste0(output_folder_TPM_outlier, "TPM_samples_PCA.pdf"))
png(paste0(output_folder_TPM_outlier, "TPM_samples_PCA.png"))
factoextra::fviz_pca_biplot(pca_result, repel = T, select.var = list(contrib = 5), label = "var") # repel = T do not overlap the text, select.var = list(contrib = 5) shows only the most 5 variable feature (variables) that contributes to separation. label = var , put label ONLY on the 5 variables
dev.off()
# dev.off()
```
# Preliminary Deconvolution Analisys ON DECONVOLUTION DATA
```{r Deconvolution}
# Deconvoltion Data Loading
input_folder_deconvolution <- "/home/francesco.massaini/Desktop/IMMUCAN_data/NSCLC2/03_Deconvolution/"
output_folder_deconvolution <- "/home/francesco.massaini/Desktop/IMMUCAN_data/NSCLC2/03_Deconvolution/"
txt_input_files_deconvolution <- c("/home/francesco.massaini/Desktop/IMMUCAN_data/NSCLC2/03_Deconvolution/all_deconvolutions_NSCLC2_TPM_noCD226_signatureCLLpatient3.txt")
files_names_deconvolution <- gsub(".txt$", "", basename(txt_input_files_deconvolution))

deconv <- read.table(txt_input_files_deconvolution, header = TRUE,  sep = '	', row.names = 1)

# Sample clustering
# pdf(paste0(output_folder_deconvolution, files_names_deconvolution, "_deconvolution_samples_heatmap.pdf"), width = 2000, height = 2000)
png(paste0(output_folder_deconvolution, files_names_deconvolution, "_deconvolution_samples_heatmap.png"), width = 2000, height = 2000)
Compute_Samples_Heatmap(t(deconv)) # double t() (here and in the function) to take into account rows
dev.off()
# dev.off()

# pdf(paste0(output_folder_deconvolution, files_names_deconvolution, "_deconvolution_samples_clustering.pdf"), width = 2000, height = 2000)
png(paste0(output_folder_deconvolution, files_names_deconvolution, "_deconvolution_samples_clustering.png"), width = 2000, height = 1000)
Compute_Samples_dendrogram(t(deconv))
dev.off()
# dev.off()

# PCA
pca_result <- PCA(deconv, scale.unit = TRUE, graph = FALSE) # t(deconv) because PCA takes rows 
fviz_eig(pca_result)

# pdf(paste0(output_folder_deconvolution, "deconvolution_samples_PCA.pdf"))
png(paste0(output_folder_deconvolution, "deconvolution_samples_PCA.png"))
factoextra::fviz_pca_biplot(pca_result, repel = T, select.var = list(contrib = 5), label = "var") # repel = T do not overlap the text, select.var = list(contrib = 5) shows only the most 5 variable feature (variables) that contributes to separation. label = var , put label ONLY on the 5 variables
dev.off()
# dev.off()

```

# Benchmark of deconvolution results vs mIF data
```{r Correlation mIF}
# loading mIF files and using the same patient names convention for IF and deconvlution results. Deleting also Tumor counts from IF data  
IF <- read.csv("/home/francesco.massaini/Desktop/IMMUCAN_data/NSCLC2/01_IF_IMC/IF1_cell_type_fraction.csv", header = 1, row.names = 1) %>%
  dplyr::select(-Tumor_count)
rownames(IF) <- rownames(IF) %>% 
  str_remove_all("-IF1-01")
  
rownames(deconv) <- rownames(deconv) %>%
  str_remove_all(pattern = ".RNA.01|.RNA.02|.RNA.04")

# Keeping only common patients and subsetting deconv and IF 
common_patients <- intersect(rownames(IF), rownames(deconv))
IF_common <- IF[common_patients,]
deconv_common <- deconv[common_patients,]

# Dividing all_markers from cell_types  
IF_cell_types <- IF_common[,1:9]
IF_markers <- IF_common[,10:15]

merged_df <- cbind(IF_cell_types, deconv_common)

# Correlation df formatted for ggplot
prova <- formatted_cors(merged_df)

formatted_cors(merged_df) %>%
  ggplot(aes(measure1, measure2, fill=r, label=round(r_if_sig,2))) +
  geom_tile() +
  labs(x = NULL, y = NULL, fill = "Pearson's\nCorrelation", title="Correlations in Mtcars",
       subtitle="Only significant Pearson's correlation coefficients shown") +
  scale_fill_gradient2(mid="#FBFEF9",low="#0C6291",high="#A63446", limits=c(-1,1)) +
  geom_text() +
  theme_classic() +
  scale_x_discrete(expand=c(0,0)) +
  scale_y_discrete(expand=c(0,0)) +
  theme(text=element_text(family="Roboto"))



ggplot(a, aes(x=B_fraction, y=XCell_B_cell)) +
  geom_point() +
  geom_smooth(method=lm , color="red", fill="#69b3a2", se=TRUE)
```

# TO DO
```{r}
 
# Analisi Risultati di deconvoluzione in termini di stackable histograms
# heatmap sui samples e PCA sulla deconvoluzione

# CellTFusion
```


# Saving file
```{r Saving file}
# Write file in the correct format for deconvolution
TPM <- rownames_to_column(TPM, "Genes") 
name <- "NSCLC2" 

write.table(TPM, file = paste0(output_folder, name,"_TPM.txt"), quote = F, sep = "\t", row.names = F)
message(paste0(output_folder, name,"_TPM.txt"))
```

