---
title: "RAW_COUNTS_TO_TPM"
author: "Francesco Massaini"
date: "2024-03-18"
output: pdf_document
---

# Inputs are the old version of Marcelo 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Imports

```{r Imports}
library(tidyverse)
library(dplyr)
library(RColorBrewer) # for plot
library(pheatmap) # for heatmaps

```

# Functions 

```{r Functions}
# library(org.Hs.eg.db) # Homo sapiens db
# columns(org.Hs.eg.db) # to look at the columns of this db

# Plots - Heatmap
Compute_Samples_Heatmap <- function(TPM){
  TPM <- as.matrix(TPM)
  
  # Utilizes the NormalizeTPM function from the ADImpute package.
  # Performs normalization on the 'TPM' data frame, considering TPM (Transcripts Per Million) values.
  # Setting 'log = T' indicates that the normalization will be done using the logarithm of TPM values.
  # This is often employed to reduce variance and approximate a normal distribution.
  # Add 1 at the log log(TPM+1) so that 0 values are propertly calculated
  
  sampleDists <- dist(TPM) #Compute distance of the matrix. DO NOT DO IT FOR GENES. dist take into account rows! So to look at the patients you need to transpose. Distance is computed with eucledian metric. Remember you need to transpose (t) the matrix because dist takes rows (and samples are into columns) 
  sampleDistMatrix <- as.matrix(sampleDists)
  colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
  pheatmap(sampleDistMatrix,    main = "Sample clustering", sub="", xlab="",
       cex.lab = 1.5, cex.axis = 1.5, cex.main = 2)
}

# Plots - Dendrogram
Compute_Samples_dendrogram <- function(TPM){
  sampleTree = hclust(dist(TPM), method = "average");
  plot(sampleTree, main = "Samples clustering", sub="", xlab="", 
       cex.lab = 1.5, cex.axis = 1.5, cex.main = 2)
}
```


# Data Loading and Plots

```{r Data Loading and plots}
# Data Loading

path <- c("/home/francesco.massaini/Desktop/IMMUCAN_data/NSCLC2/03_Deconvolution/all_deconvolutions_NSCLC2_TPM.txt")
files_names <- gsub(".txt$", "", basename(path))
folders_names <- strsplit(path, "IMMUCAN_data")
folders_names <- folders_names[[1]][2]
folders_names <- strsplit(folders_names, split = files_names)

# EDA
for (i in 1:length(path)) {
  TPM <- read.table(path[i], header = TRUE,  sep = '	', row.names = 1)
  pdf(paste0("../IMMUCAN_data", folders_names[[i]][1], files_names[i],"_outliers"), width = 16) # folders_names[[i]][1] double square bracket to access to the i vector, single bracket to access to the first value of the i vector 
  Compute_Samples_Heatmap(TPM)
  Compute_Samples_dendrogram(TPM)
  dev.off()
}
```
