
---
title: "NSCLC2"
author: "Francesco Massaini"
date: "2024-03-28"
output: html_document
editor_options: 
  chunk_output_type: inline
---

# Imports
```{r Imports}
suppressMessages(library(dplyr)) 
suppressMessages(library(tibble))
suppressMessages(library(tidyr))
suppressMessages(library(org.Hs.eg.db)) # Homo sapiens db
suppressMessages(library(stringr))
suppressMessages(library(RColorBrewer)) # for plot
suppressMessages(library(pheatmap)) # for heatmaps
suppressMessages(library(ADImpute)) # This package provides functions to compute TPM
suppressMessages(library(ggplot2))
suppressMessages(library(FactoMineR))
suppressMessages(library(factoextra))
suppressMessages(library(survival))
suppressMessages(library(ranger))
suppressMessages(library(ggfortify))
suppressMessages(library(rlang))
suppressMessages(library(purrr))
suppressMessages(library(rio))
suppressMessages(library(uwot))
suppressMessages(library(DESeq2))
```


# Functions
```{r Functions}
source("./Functions.R")
```

# Path and folders
```{r Data loading}
# Imposta il percorso della cartella
input_folder <- "../IMMUCAN_data/NSCLC2/01_Raw_Counts/star_counts"
output_folder_TPM <- "../IMMUCAN_data/NSCLC2/02_TPM/"
output_folder_TPM_outlier <- "../IMMUCAN_data/NSCLC2/02_Plot_Outliers/"
output_folder_deconvolution <- "../IMMUCAN_data/NSCLC2/03_Deconvolution/Whitout_CD226_and_without_patient3/"
output_folder_CellTFusion <- "../IMMUCAN_data/NSCLC2/04_CellTFusion/Whitout_CD226_and_without_patient3/" 



# Ottieni tutti i file .txt nella cartella
txt_input_files <- list.files(path = input_folder, pattern = "\\.txt$", full.names = TRUE)

files_names <- gsub(".txt$", "", basename(txt_input_files))
samples_names = str_split_i(files_names, "_", 1)

```

# Loading Deconvolution Data
```{r Loading Deconvolution}
# Load clinical data 
clinical = read.csv("../IMMUCAN_data/NSCLC2/01_Clinical_Data/Daniel/NSCLC2_for_R_update_2024.csv") %>%
  dplyr::select(immucan_id, stage, death, neo_adjuvant_treatment, adjuvant_treatment, simple_histology, long_survivors, TIL_score, side_localization, gender) %>%
  column_to_rownames(var = "immucan_id") 

# Loading Deconvolution results
deconv <- read.table("../IMMUCAN_data/NSCLC2/03_Deconvolution/Whitout_CD226_and_without_patient3/all_deconvolutions_NSCLC2_TPM_withoutCD226_withoutPatient3.txt", header = TRUE,  sep = '	', row.names = 1)
rownames(deconv) = gsub(pattern = "-FIXT.*", 
                              replacement = "",
                              x = rownames(deconv))

# Only common patients
common_samples <- intersect(rownames(clinical), rownames(deconv)) 

deconv <- deconv[common_samples,]
clinical = clinical[common_samples,]
```

# Preliminary Deconvolution Analisys ON DECONVOLUTION DATA
## Sample Heatmap
NOTE: Expression df must be genes as rows and patients as column. Clinical df must be patients as rows and feature as columns 
```{r, fig.width=10, fig.height=10, Heatmap}
  # Ensure same patients order

# Heatmap on TPM, groups and outliers 
# pdf(paste0(output_folder_TPM_outlier, "TPM_samples_heatmap.pdf"), width = 16, height = 16)
Compute_Samples_Heatmap(t(deconv),  sample_feat_df = clinical, main_title = "Heatmap samples vs samples - Euclidian distance matrix on TPM data") 
# dev.off()

```

## Sample Dendrogram
```{r}
# Sample dendrograms, colored by relevant clinical feature
# pdf(paste0(output_folder_TPM_outlier, "TPM_samples_dendrogram.pdf"), width = 16, height = 10)
for (feat in colnames(clinical)){
  tree = Compute_Samples_dendrogram(t(deconv),  sample_feat_df = clinical, feat_column = feat, main_title = "Sample dendrogram - Euclidian distance matrix on TPM data")
  print(tree)
}
# dev.off()
```

## PCA biplot
```{r}
# PCA biplot on TPM

# Ensure to merge in the same order TPM and clinical values and traspose 
tmp = dfs_same_patients_same_order(t(deconv), clinical, expr_patients_on_rows = TRUE, clinical_patients_on_rows = TRUE)
deconv = tmp[["expression_data"]]
clinical = tmp[["clinical_data"]] %>%
  replace(is.na(.), "NA") # Replace NA with missing to show NA values on fviz_pca_biplot

# Compute PCA
pca_result <- FactoMineR::PCA(deconv, scale.unit = TRUE, graph = FALSE)  
fviz_eig(pca_result) # Scree plot: explained variance by PC

# pdf(paste0(output_folder_TPM_outlier, "TPM_samples_PCA.pdf"))
for (feat in colnames(clinical)){
  p = factoextra::fviz_pca_biplot(pca_result, repel = T, select.var = list(contrib = 5), label = "var",
                              habillage = as.factor(clinical[,feat]),
                              addEllipses = T, ellipse.level=0.95, palette = "Dark2", 
                              legend.title = feat,
                              ggtheme = theme_minimal())
  print(p)
}
# repel = T do not overlap the text, select.var = list(contrib = 5) shows only the most 5 variable feature (variables) that contributes to separation. label = var , put label ONLY on the 5 variables
# dev.off()
```

## Umap 
```{r}
# UMAP on TPM
clinical <- clinical %>% 
  mutate(across(everything(), ~ifelse(. == "MISSING", NA, .))) # Restore NA 

umap_result <- as.data.frame(umap(deconv, n_neighbors = 8, min_dist = 0.1, metric = "euclidean")) # t() it's not necessary beacuse TPM has been already transposed
colnames(umap_result) <- c("UMAP1", "UMAP2")
umap_result = rownames_to_column(umap_result, var = "samples")
clinical_umap = rownames_to_column(clinical, var = "samples")
umap_result = left_join(umap_result, clinical_umap, by = "samples")

for (feat in colnames(clinical_umap)[-1]){
  col = c("UMAP1", "UMAP2", feat)
  umap_ggplot = dplyr::select(umap_result, all_of(col))
  colnames(umap_ggplot)[3] = "feat" 
  umap_plot <- ggplot(umap_ggplot, aes(x = UMAP1, y = UMAP2, color = feat)) +
    geom_point(size = 3) +
    labs(title = "UMAP of TPM Data", x = "UMAP1", y = "UMAP2") +
    theme_minimal() + 
    labs(color = feat)
    print(umap_plot)
}


```
# Correlation of deconvolution and IDA
```{r}
# Load MetaSample and MetaGene from BIODICA analysis. 
metasample_df <- read.table("/home/francesco.massaini/Projects/BIODICA/work/TPM_NSCLC2_Biodica_meanDuplGenes_ICA/TPM_NSCLC2_Biodica_meanDuplGenes_ica_A.xls", header = TRUE, row.names = 1)
metagene_df <- read.table("/home/francesco.massaini/Projects/BIODICA/work/TPM_NSCLC2_Biodica_meanDuplGenes_ICA/TPM_NSCLC2_Biodica_meanDuplGenes_ica_S.xls", header = TRUE, row.names = 1)

# Correlation
create_correlation_plot(data1 = deconv, data2 = metasample_df, correlation_type = "pearson", r_threshold = 0.7, p_threshold = 0.05)


```
```
