---
title: "NSCLC2_clinical_analysis"
author: "Francesco Massaini"
date: "2024-06-11"
output: html_document
---

# Imports
```{r Imports}
suppressMessages(library(dplyr)) 
suppressMessages(library(tibble))
suppressMessages(library(tidyr))
suppressMessages(library(org.Hs.eg.db)) # Homo sapiens db
suppressMessages(library(stringr))
suppressMessages(library(RColorBrewer)) # for plot
suppressMessages(library(pheatmap)) # for heatmaps
suppressMessages(library(ADImpute)) # This package provides functions to compute TPM
suppressMessages(library(ggplot2))
suppressMessages(library(FactoMineR))
suppressMessages(library(factoextra))
suppressMessages(library(survival))
suppressMessages(library(ranger))
suppressMessages(library(ggfortify))
suppressMessages(library(rlang))
suppressMessages(library(purrr))
suppressMessages(library(rio))
suppressMessages(library(uwot))
suppressMessages(library(DESeq2))
```


# Functions
```{r Functions}
source("./Functions.R")
```

# Load clinical
```{r}
load("../IMMUCAN_data/BC2/02_TPM/BC2_estimated_TPM_fromAndrea.RData")

clinical_all_columns = read.delim("../IMMUCAN_data/BC2/01_Clinical_Data/BC2_clinical_export_20240602.tsv", sep = "\t") %>%
  dplyr::filter(immucan_sample_id %in% colnames(gexp_tpm)) %>%
  dplyr::select(where(~ sum(!is.na(.)) >= 20))
cat("Numb of samples:", length(unique(clinical_all_columns$immucan_sample_id)) , "\n Not present samples:", setdiff(colnames(gexp_tpm), clinical_all_columns$immucan_sample_id))

relevant_clinical_columns = c("immucan_patient_id",
      "immucan_sample_id",
      "surgery_days_after_diag",
      "sampling_days_after_diag",
      "lymphocyte_infiltration",
      "PCR",
      # "medical_review_end_point", # full of "pCR (e.g. surgery)". I'm not sure what is the difference with column PCR, perhaps on different time point?
      # "medical_review_days_after_diag",
      "residual_cancer_burden",
      "residual_disease",
      # "treatment_setting", # Empty column on the same samples of RNAseq  
      # "sex", # obviously not so interesting for BC
      # "HER2_status", # all negative
      # "ER_status", # all negative
      # "PR_status", # only 1 patient positive
      "KI67_status",
      "laterality",
      # "disease_evolution", # only three 1 values
      "stage",
      "N_stage",
      # "M_stage", # only cM0 or unknown 
      "T_stage")


# Filter clinical with only relevant columns and mutate absent ("") values to NA
clinical = clinical_all_columns[, relevant_clinical_columns] %>%
  dplyr::select(-all_of(c("surgery_days_after_diag","sampling_days_after_diag", "immucan_patient_id"))) %>% # remove even immucan_patient_id for better further rapresentations
  mutate(PCR = if_else(PCR == "", NA, PCR)) %>%
  mutate(stage = if_else(stage == "", NA, stage)) %>%
  mutate(lymphocyte_infiltration = if_else(lymphocyte_infiltration == "", NA, lymphocyte_infiltration)) %>%
  mutate(lymphocyte_infiltration = if_else(lymphocyte_infiltration == "Not Applicable", "Not applicable", lymphocyte_infiltration)) %>%
  mutate(residual_cancer_burden = if_else(residual_cancer_burden == "", NA, residual_cancer_burden)) %>%
  mutate(residual_disease = if_else(PCR == "", NA, residual_disease)) %>%
  column_to_rownames(var = "immucan_sample_id")
```

# Fisher/chi tests
```{r}

for (feat1 in colnames(clinical)){
  clinical_features = colnames(clinical)[colnames(clinical) != feat1]
  for (feat2 in clinical_features){
    selected = dplyr::select(clinical, feat1 , feat2)
    contingency_table = table(selected)
    chi_result <- chisq.test(as.matrix(contingency_table))
      if (!is.na(chi_result$p.value) && chi_result$p.value < 0.95) {
        print(paste(feat2, chi_result$p.value))
        print(contingency_table)
        mosaicplot(contingency_table + 0.1,
                   main = "Mosaic plot",
                   sub = paste("P-value:", format(chi_result$p.value, digits = 2)),
                   color = TRUE
                  )
      } else{
      cat(feat2, "No Significance\n")
      }
  }
}  
```
```{r}
clinical_filtered = clinical %>%
  dplyr::filter(PCR != "Unknown")
specific_contingency = table(clinical[,"laterality"], clinical[,"PCR"])
colnames(specific_contingency) = c("laterality", "PCR", "Freq")

chi_result_specific <- chisq.test(as.matrix(specific_contingency))

mosaicplot(specific_contingency + 0.1,
                   main = "Mosaic plot",
                   sub = paste("P-value:", format(chi_result_specific$p.value, digits = 2)),
                   color = TRUE
                  )
```




# Kaplan-Meier
```{r}
clinical_all_columns = read.delim("../IMMUCAN_data/BC2/01_Clinical_Data/BC2_clinical_export_20240602.tsv", sep = "\t") %>%
  dplyr::filter(immucan_sample_id %in% colnames(gexp_tpm)) %>%
  dplyr::select(where(~ sum(!is.na(.)) >= 20))


clinical_surv = clinical_all_columns[, c("immucan_sample_id",
      "surgery_days_after_diag",
      "sampling_days_after_diag",
      "medical_review_end_point", # full of "pCR (e.g. surgery)" and they don't match PCR column. I'm not sure what is the difference with column PCR, perhaps on different time point?
      "medical_review_days_after_diag", 
      "PCR",
      "lymphocyte_infiltration", 
      "stage",
      "residual_cancer_burden",
      "residual_disease")]

# Filter clinical with only relevant columns and mutate absent ("") values to NA
clinical_surv = clinical_surv %>%
  mutate(PCR = if_else(PCR == "", NA, PCR)) %>%
  mutate(PCR = if_else(PCR == "Unknown", NA, PCR)) %>%
  mutate(stage = if_else(stage == "", NA, stage)) %>%
  mutate(lymphocyte_infiltration = if_else(lymphocyte_infiltration == "", NA, lymphocyte_infiltration)) %>%
  mutate(lymphocyte_infiltration = if_else(lymphocyte_infiltration == "Not Applicable", "Not applicable", lymphocyte_infiltration)) %>%
  mutate(residual_cancer_burden = if_else(residual_cancer_burden == "", NA, residual_cancer_burden)) %>%
  mutate(residual_disease = if_else(PCR == "", NA, residual_disease)) %>%
  mutate(medical_review_end_point_logical = if_else(medical_review_end_point == "pCR (e.g. surgery)", TRUE, FALSE)) %>%
  column_to_rownames(var = "immucan_sample_id")

km_trt_fit <- survfit(Surv(medical_review_days_after_diag, medical_review_end_point_logical) ~ 1, data=clinical_surv)
autoplot(km_trt_fit)

km_trt_fit <- survfit(Surv(medical_review_days_after_diag, medical_review_end_point_logical) ~ PCR, data=clinical_surv)
library(survminer)
ggsurvplot(
  km_trt_fit,                      # modello survfit
  data = clinical_surv,            # dataset
  pval = TRUE,                     # mostra il p-value del test log-rank
  conf.int = TRUE,                 # mostra l'intervallo di confidenza
  palette = c("#E7B800", "#2E9FDF"),  # colori delle linee
  risk.table = TRUE                # aggiunge una tabella dei rischi
)
clinical_surv = na.omit(clinical_surv)
km_trt_fit <- survfit(Surv(medical_review_days_after_diag, medical_review_end_point_logical) ~ lymphocyte_infiltration, data=clinical_surv)
autoplot(km_trt_fit)

km_trt_fit <- survfit(Surv(medical_review_days_after_diag, medical_review_end_point_logical) ~ stage, data=clinical_surv)
autoplot(km_trt_fit)

km_trt_fit <- survfit(Surv(medical_review_days_after_diag, medical_review_end_point_logical) ~ residual_disease, data=clinical_surv)
autoplot(km_trt_fit)
```

